photon_triggers:
  triggers:
    - name: HLT_Photon22_R9Id90_HE10_IsoM
      threshold: 21.99
      #Take 10% more, so that we are on the plateau (the pT in the name is the one at the middle of the turn-on curve, so at 50% efficiency).
    - name: HLT_Photon30_R9Id90_HE10_IsoM
      threshold: 29.99
    - name: HLT_Photon36_R9Id90_HE10_IsoM
      threshold: 35.99
    - name: HLT_Photon50_R9Id90_HE10_IsoM
      threshold: 49.99
    - name: HLT_Photon75_R9Id90_HE10_IsoM
      threshold: 74.99
    - name: HLT_Photon90_R9Id90_HE10_IsoM
      threshold: 89.99
    - name: HLT_Photon120_R9Id90_HE10_IsoM
      threshold: 119.99
    - name: HLT_Photon165_R9Id90_HE10_IsoM
      threshold: 164.99

  photon_prescale_map: data/Prescales/photon_prescales_2016.yaml

