photon_triggers:
  triggers:
    - name: HLT_Photon50_R9Id90_HE10_IsoM
      threshold: 49.9
    - name: HLT_Photon75_R9Id90_HE10_IsoM
      threshold: 74.9
    - name: HLT_Photon90_R9Id90_HE10_IsoM
      threshold: 89.9
    - name: HLT_Photon120_R9Id90_HE10_IsoM
      threshold: 119.9
    - name: HLT_Photon165_R9Id90_HE10_IsoM
      threshold: 164.9
    - name: HLT_Photon200
      threshold: 199.9

  photon_prescale_map: data/Prescales/photon_prescales_2017.yaml

