tree_name: tnpPhoIDs/fitter_tree
tag-selections:
  - tag_Ele_pt > 35
  - tag_Ele_IsoMVA94XV2
  #- ph_PFIsoAll/ph_et < 0.15
  #- passingMVA94XV2wp90
  - passingCutBasedTight94XV2
  - ph_abseta < 2.5

photon-pt-points:
  - 50
  - 75
  - 90
  - 120
  - 165
  - 200

photon50:
  flag:
    - Photon50passTrigger
    - passHltPhoton50
  prescale: photon50prescale

photon75:
  flag:
    - Photon75passTrigger
    - passHltPhoton75
  prescale: photon75prescale

photon90:
  flag:
    - Photon90passTrigger
    - passHltPhoton90
  prescale: photon90prescale

photon120:
  flag:
    - Photon120passTrigger
    - passHltPhoton120
  prescale: photon120prescale

photon165:
  flag:
    - Photon165passTrigger
    - passHltPhoton165
  prescale: photon165prescale

photon175:
  flag:
    - Photon175passTrigger
    - passHltPhoton175
  prescale: 1

photon200:
  flag:
    - Photon200passTrigger
    - passHltPhoton200
  prescale: 1
